name: priyobanskhali
description: Banskhalir shekhor theke shekhore
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+12

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.2.1
  google_fonts: ^6.1.0

  #  flutter_local_notifications: ^18.0.1

  basic_utils: ^5.4.2
  #  carousel_pro_nullsafety: ^2.0.0
  url_launcher: ^6.1.7
  fluttertoast: ^8.1.2
  get: ^4.6.5
  image_picker: ^1.0.4
  image_cropper: ^9.0.0
  file_picker: ^8.1.2

  cached_network_image: ^3.2.3
  flutter_cached_pdfview: ^0.4.1
  multi_select_flutter: ^4.1.3
  dotted_border: ^2.0.0+3
  flutter_spinkit: ^5.1.0
  http: ^1.2.0
#  flutter_bkash: ^0.2.0
  intl: ^0.20.2
  share_plus: ^10.0.2
  path_provider: ^2.1.2
#  social_share: ^2.3.1
  flutter_inappwebview: ^6.1.5
  iconsax: ^0.0.8
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - shorebird.yaml
