name: priyobanskhali
description: Banskhalir shekhor theke shekhore
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+10

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  basic_utils: ^5.4.2
  #  carousel_pro_nullsafety: ^2.0.0
  url_launcher: ^6.1.7
  fluttertoast: ^8.1.2
  get: ^4.6.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  file_picker: ^6.1.1

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10

  cached_network_image: ^3.2.3
  flutter_cached_pdfview: ^0.4.1
  multi_select_flutter: ^4.1.3
  dotted_border: ^2.0.0+3
  flutter_spinkit: ^5.1.0
  http: ^1.1.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^16.1.0
  carousel_slider: ^4.2.1
  flutter_bkash: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - shorebird.yaml
