name: priyobanskhali
description: Banskhalir shekhor theke shekhore
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+14

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^1.0.2

  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  google_fonts: ^6.2.1
  flutter_local_notifications: ^19.0.0
  basic_utils: ^5.8.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  get: ^4.7.2
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  file_picker: ^10.1.0

  cached_network_image: ^3.4.1
  flutter_cached_pdfview: ^0.4.3
  multi_select_flutter: ^4.1.3
  dotted_border: ^2.1.0
  flutter_spinkit: ^5.2.1
  http: ^1.3.0
  intl: ^0.20.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_inappwebview: ^6.1.5
  iconsax: ^0.0.8
  in_app_update: ^4.2.3
  googleapis_auth: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/data/
    - assets/logo/
    - assets/images/
    - shorebird.yaml
